---
- name: Lookup plugin demo
  hosts: nodes
  gather_facts: false
  vars:
    auth_key: "{{ lookup('file', '/home/vagrant/.ssh/id_ed25519.pub') }}"

  tasks:
    - name: control node Key
      debug:
        var: auth_key

    - name: Add the key to the vagrant account
      ansible.posix.authorized_key:
        user: vagrant
        state: present
        key: "{{ auth_key }}"
