# -*- mode: ruby -*-
# vi: set ft=ruby :

BOX_NAME    = "nobreak-labs/ubuntu-noble"
BOX_VERSION = "24.04.4"

NODES = [
  { name: "terraform",  ip: "192.168.56.60", cpus: 2, memory: 3072 },

]

Vagrant.configure("2") do |config|
  config.vm.synced_folder ".", "/vagrant", disabled: true

  NODES.each do |node|
    config.vm.define node[:name] do |vm|
      vm.vm.box         = BOX_NAME
      vm.vm.box_version = BOX_VERSION
      vm.vm.hostname    = node[:name]
      vm.vm.network "private_network", ip: node[:ip]

      vm.vm.provider "virtualbox" do |vb|
        vb.name   = node[:name]
        vb.cpus   = node[:cpus]
        vb.memory = node[:memory]
      end
    end
  end
end
